### ISSUE TITLE
Im lost

### ISSUE THREAD

**Issue by sagudd** [macias100/quizizz-hack#11]
Any video who show me how to do it I dont know how to add bot. Im lost pls help.
Im lost after "Invite the bot to a server (that you own) by pasting that link in a browser" because when I paste the link it says that I don have a bot. Then I go to bot and ad idk some bot but now I dont know what to do next.

**Comment by sagudd** [comment]
Or can somebody make it for me through team viewer.

**Comment by macias100** [comment]
On discordapp.com/developers go to your application, then bot -> add a bot

**Comment by sagudd** [comment]
I did it but bot is not active. And how to use

**Comment by sagudd** [comment]
Where to find token of discord bot

**Comment by macias100** [comment]
bot-> copy bot token, then put it inside index.js
