### ISSUE TITLE
Join Game From Link and not Join Code

### ISSUE THREAD

**Issue by Element21** [macias100/quizizz-hack#4]
Hi Macias,

I am in a quizziz class and assigned games do not have a game code associated with them, but they have a game string ex.. https://quizizz.com/join/game/U2FsdGVkX1%252FQebkXaHaiv%252BP7vf6SuyODCDSr6wxEuyTHEZr3SXIvVc9jYWkxlzOZw4gsLee5Tyi75YTIXfnK1g%253D%253D
Can we still get answers from these types of games?

Thanks,
Aiden

**Comment by macias100** [comment]
Currently no, but i will be working on this in future updates

**Comment by Element21** [comment]
Thanks!
