### ISSUE TITLE
When using !link discord messages don't display correctly

### ISSUE THREAD

**Issue by Element21** [macias100/quizizz-hack#7]
Hello again,

When using the new !link feature the messages do not display right. Here is an image of my problem (http://imgur.com/a/1XHQx14). Is this a discord bug or your bot?

Thanks,
Aiden

**Comment by macias100** [comment]
Does anything logs in console? For me it looks like an issue connected to the discord or the link as the embeds are send but dont show up (First embed with image from link to quizizz doesn't show aswell). Try couple more times if this still happens contact me on dicord: Macias#7761

**Comment by Element21** [comment]
The only output is
'''
Bot is up
[ '5e8a735b7db0e5001b640dc2' ]
joined!
'''
Another thing that happens is I can see the text in my notifications from discord, I just cannot read them from the actual server, very weird.

**Comment by macias100** [comment]
So you can see the text that is included in embeds in notifications but on in the server itself? If so then it's a 100% related issue to the discord, also check if the bot has permissions to send embedded messages or the channel allows to send embedded messages. You can try the bot on other server too.

**Comment by Element21** [comment]
Ok, so I set it to 'console.log(`Question: ${$.text()} \n \n Answer: ${answer}`);' and I recive

Question: All imaginary roots comes in pairs. 
 
 Answer: True
Question: Write the polynomial in STANDARD form given the following zeros. x = -2, 1, 4 
 
 Answer: f(x) = x3 - 3x2 - 6x + 8
Question: Which of the following would be a root with 3i?  
 
 Answer: -3i
Question: Which of the following would be the correct FACTORED form with roots -2, 5i, and 6? 
 
 Answer: f(x) = (x-6)(x+2)(x+5i)(x-5i)
Question: If a+bi is a root of a polynomial, then _______ is also a root.  
 
 Answer: a-bi
Question: Use the Complex Conjugate Root Theorem to state another complex solution. Given that -2-5i is a root.  
 
 Answer: -2+5i
Question: Write a polynomial function of least degree with integral coefficients that has the given zeros. 
 
 Answer: A
Question: Find a polynomial function of degree 3 with zeros 3i and -2. 
 
 Answer: P(x) = x3 + 2x2 + 9x + 18
Question: Write the polynomial with the given zeros 
 
 Answer: A
Question: Write a polynomial function of least degree with integral coefficients that has the given zeros:-1, 5, -3+2i 
 
 Answer: f(x) = x4 + 2x3 - 16x2 - 82x - 65

So I can confirm it is something with my discord or the way the bot sends the message

**Comment by Element21** [comment]
I have given the bot admin privileges on a new server and it still does not embed right. At this point I can't do much more.

**Comment by Element21** [comment]
I have also tried using a game code and it still does not send and embeded message

**Comment by Element21** [comment]
I have found a solution. I replace RichEmbed with just a simple test message/

'                          let text = `Question: ${$.text()} \n \n Answer: ${answer}`
                          //   .setImage(media);
                          message.channel.send(text);
'

**Comment by Element21** [comment]
let text = `Question: ${$.text()} \n \n Answer: ${answer}`
                          //   .setImage(media);
                          message.channel.send(text);

**Comment by macias100** [comment]
So as this is a purely discord related glitch i think i can close it now, if you want you can contact discord support why can't you see embedded messages. https://support.discordapp.com/hc
